name: Cpanel Deploy

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - name: Install dependencies
      run: git clone ssh://aneuropean@aneuropean.com/home/aneuropean/webhook-test.aneuropean.com/project